import { Tenant, Category, Product, FilterOption } from '@/types';

export const FILTER_OPTIONS: FilterOption[] = [
  { id: 'vegano', label: 'Vegano', icon: '🌱', color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30' },
  { id: 'vegetariano', label: 'Vegetariano', icon: '🧀', color: 'bg-green-500/20 text-green-400 border-green-500/30' },
  { id: 'sem_lactose', label: 'Sem Lactose', icon: '🥛', color: 'bg-blue-500/20 text-blue-400 border-blue-500/30' },
  { id: 'sem_gluten', label: 'Sem Glúten', icon: '🌾', color: 'bg-amber-500/20 text-amber-400 border-amber-500/30' },
  { id: 'apimentado', label: 'Apimentado', icon: '🌶️', color: 'bg-red-500/20 text-red-400 border-red-500/30' },
  { id: 'fit', label: 'Fit / Saudável', icon: '💪', color: 'bg-teal-500/20 text-teal-400 border-teal-500/30' },
  { id: 'zero_acucar', label: 'Zero Açúcar', icon: '❌', color: 'bg-purple-500/20 text-purple-400 border-purple-500/30' },
  { id: 'artesanal', label: 'Artesanal', icon: '👑', color: 'bg-orange-500/20 text-orange-400 border-orange-500/30' },
  { id: 'premium', label: 'Chef Premium', icon: '⭐', color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30' },
];

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 't-1',
    name: 'Calixto Burger & Grill',
    slug: 'calixto-burger',
    logo_url: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=300&h=300&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=500&fit=crop',
    description: 'Hamburgueria gourmet com carnes nobres grelhadas na brasa, molhos especiais artesanais e milkshakes supremos.',
    phone: '(11) 98888-7777',
    whatsapp: '5511988887777',
    instagram: '@calixtoburger',
    facebook: 'calixtoburgeroficial',
    tiktok: '@calixtoburger',
    website: 'https://calixtoburger.com.br',
    address: 'Av. Paulista, 1500 - Jardins, São Paulo - SP',
    google_maps_url: 'https://maps.google.com',
    opening_hours: {
      mon_fri: '11:30 - 23:00',
      sat_sun: '12:00 - 01:00',
    },
    subscription_status: 'active',
    subscription_plan: 'annual',
    expires_at: '2027-12-31T23:59:59.000Z',
    theme_config: {
      primary_color: '#FF5722',
      mode: 'dark',
      style: 'glass',
    },
    created_at: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 't-2',
    name: 'Bistrô Bellíssimo',
    slug: 'bistro-bellissimo',
    logo_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=300&h=300&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&h=500&fit=crop',
    description: 'Autêntica culinária italiana. Massas artesanais feitas diariamente pelo Chef, risotos e carta de vinhos selecionados.',
    phone: '(11) 97777-6666',
    whatsapp: '5511977776666',
    instagram: '@bistrobellissimo',
    address: 'Rua Oscar Freire, 890 - Cerqueira César, SP',
    opening_hours: {
      mon_fri: '12:00 - 15:00, 19:00 - 23:30',
      sat_sun: '12:00 - 00:00',
    },
    subscription_status: 'active',
    subscription_plan: 'monthly',
    expires_at: '2026-09-01T23:59:59.000Z',
    theme_config: {
      primary_color: '#E11D48',
      mode: 'dark',
      style: 'glass',
    },
    created_at: '2025-02-01T10:00:00.000Z',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 'c-1', tenant_id: 't-1', name: '🔥 Mais Vendidos', slug: 'mais-vendidos', sort_order: 1, is_active: true },
  { id: 'c-2', tenant_id: 't-1', name: '🍔 Burgers Grelhados', slug: 'burgers-grelhados', sort_order: 2, is_active: true },
  { id: 'c-3', tenant_id: 't-1', name: '🍟 Porções & Acompanhamentos', slug: 'porcoes', sort_order: 3, is_active: true },
  { id: 'c-4', tenant_id: 't-1', name: '🥤 Bebidas & Shakes', slug: 'bebidas', sort_order: 4, is_active: true },
  { id: 'c-5', tenant_id: 't-1', name: '🍰 Sobremesas Artesanais', slug: 'sobremesas', sort_order: 5, is_active: true },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p-1',
    tenant_id: 't-1',
    category_id: 'c-1',
    name: 'Konnexy Supreme Bacon Burger',
    slug: 'konnexy-supreme-bacon-burger',
    description: 'Burger de 180g de Blend Angus grelhado no fogo, triplo queijo cheddar fatiado, bacon artesanal super crocante, cebola caramelizada no whiskey e molho especial em pão brioche amanteigado.',
    price: 42.90,
    promo_price: 36.90,
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&fit=crop',
      'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&fit=crop',
      'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&fit=crop'
    ],
    ingredients: ['Blend Angus 180g', 'Bacon defumado em lenha de macieira', 'Triple Cheddar', 'Cebola caramelizada', 'Molho secreto Konnexy', 'Pão Brioche'],
    weight: '380g',
    calories: 780,
    prep_time_min: 15,
    serves: 1,
    is_available: true,
    sort_order: 1,
    is_featured: true,
    is_bestseller: true,
    is_new: false,
    is_promo: true,
    filters: ['artesanal', 'premium'],
  },
  {
    id: 'p-2',
    tenant_id: 't-1',
    category_id: 'c-2',
    name: 'Smash Double Trufado',
    slug: 'smash-double-trufado',
    description: 'Dois discos de smash burger 90g com crosta bem selada, queijo emmental derretido, maionese trufada e picles artesanal.',
    price: 38.00,
    image_url: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&fit=crop'],
    ingredients: ['2x Smash 90g', 'Queijo Emmental', 'Maionese de trufas brancas', 'Picles de pepino da casa'],
    weight: '300g',
    calories: 640,
    prep_time_min: 12,
    serves: 1,
    is_available: true,
    sort_order: 2,
    is_featured: false,
    is_bestseller: true,
    is_new: true,
    is_promo: false,
    filters: ['artesanal', 'premium'],
  },
  {
    id: 'p-3',
    tenant_id: 't-1',
    category_id: 'c-2',
    name: 'Veggie Green Beyond Burger',
    slug: 'veggie-green-beyond-burger',
    description: 'Hambúrguer 100% vegetal Beyond Meat, queijo vegano derretido, alface americana, tomate confit e maionese verde de ervas finas sem lactose.',
    price: 39.90,
    image_url: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=800&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=800&fit=crop'],
    ingredients: ['Beyond Burger 150g', 'Queijo de Castanha', 'Tomate Confit', 'Maionese Verde Vegana'],
    weight: '320g',
    calories: 490,
    prep_time_min: 15,
    serves: 1,
    is_available: true,
    sort_order: 3,
    is_featured: true,
    is_bestseller: false,
    is_new: false,
    is_promo: false,
    filters: ['vegano', 'sem_lactose', 'fit'],
  },
  {
    id: 'p-4',
    tenant_id: 't-1',
    category_id: 'c-3',
    name: 'Batata Rustica Trufada com Parmesão',
    slug: 'batata-rustica-trufada',
    description: 'Batatas cortadas à mão com casca, fritas na hora, aromatizadas com azeite de trufas brancas e cobertas com queijo parmesão ralado e alecrim fresco.',
    price: 28.90,
    promo_price: 24.90,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&fit=crop'],
    ingredients: ['Batatas Asterix', 'Azeite de trufa', 'Parmesão 24 meses', 'Alecrim fresco'],
    weight: '400g',
    calories: 520,
    prep_time_min: 10,
    serves: 2,
    is_available: true,
    sort_order: 1,
    is_featured: false,
    is_bestseller: true,
    is_new: false,
    is_promo: true,
    filters: ['sem_gluten', 'artesanal'],
  },
  {
    id: 'p-5',
    tenant_id: 't-1',
    category_id: 'c-4',
    name: 'Milkshake de Nutella com Ninho e Chantilly',
    slug: 'milkshake-nutella-ninho',
    description: 'Milkshake cremoso preparado com sorvete artesanal de baunilha, generosa camada de Nutella pura, Leite Ninho e topo de chantilly com avelãs tostadas.',
    price: 26.00,
    image_url: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&fit=crop'],
    ingredients: ['Gelato baunilha', 'Nutella', 'Leite Ninho', 'Chantilly fresco', 'Avelãs'],
    volume: '500ml',
    calories: 680,
    prep_time_min: 7,
    serves: 1,
    is_available: true,
    sort_order: 1,
    is_featured: true,
    is_bestseller: true,
    is_new: false,
    is_promo: false,
    filters: ['artesanal', 'premium'],
  },
];

export const MOCK_ANALYTICS = {
  total_views: 12450,
  qr_scans: 3820,
  whatsapp_clicks: 1490,
  top_products: [
    { name: 'Konnexy Supreme Bacon Burger', views: 3410, image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&fit=crop' },
    { name: 'Batata Rustica Trufada', views: 2890, image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=200&fit=crop' },
    { name: 'Milkshake de Nutella', views: 2150, image_url: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=200&fit=crop' },
  ],
  recent_activity: [
    { time: 'Há 3 min', type: 'whatsapp', details: 'Pedido de Mesa 04 enviado para WhatsApp (R$ 104,80)' },
    { time: 'Há 12 min', type: 'qr', details: 'Scan de QR Code da Mesa 08' },
    { time: 'Há 18 min', type: 'view', details: 'Acesso direto via link /calixto-burger' },
    { time: 'Há 25 min', type: 'whatsapp', details: 'Pedido de Delivery enviado via WhatsApp (R$ 68,90)' },
  ],
};
