import { Category, Product, TenantThemeConfig } from '@/types';

export interface SectorTemplate {
  id: string;
  name: string;
  icon: string;
  description: string;
  theme: TenantThemeConfig;
  defaultLogo: string;
  defaultBanner: string;
  categories: Array<{ name: string; slug: string; sort_order: number }>;
  products: Array<{
    name: string;
    slug: string;
    category_slug: string;
    description: string;
    price: number;
    promo_price?: number;
    image_url: string;
    ingredients?: string[];
    filters?: string[];
    is_bestseller?: boolean;
    is_featured?: boolean;
  }>;
}

export const SECTOR_TEMPLATES: SectorTemplate[] = [
  {
    id: 'hamburgueria',
    name: 'Hamburgueria Artesanal',
    icon: '🍔',
    description: 'Ideal para hamburguerias gourmet, smash burgers, porções crocantes e milkshakes.',
    theme: { primary_color: '#FF5722', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=500&fit=crop',
    categories: [
      { name: '🔥 Mais Vendidos', slug: 'mais-vendidos', sort_order: 1 },
      { name: '🍔 Burgers Grelhados', slug: 'burgers-grelhados', sort_order: 2 },
      { name: '🍟 Porções & Acompanhamentos', slug: 'porcoes', sort_order: 3 },
      { name: '🥤 Shakes & Bebidas', slug: 'shakes', sort_order: 4 },
      { name: '🍰 Sobremesas Artesanais', slug: 'sobremesas', sort_order: 5 },
    ],
    products: [
      {
        name: 'Supreme Bacon Burger',
        slug: 'supreme-bacon-burger',
        category_slug: 'mais-vendidos',
        description: 'Blend Angus 180g grelhado no fogo, triplo cheddar fatiado, bacon crocante em lenha e maionese artesanal.',
        price: 42.90,
        promo_price: 36.90,
        image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&fit=crop',
        ingredients: ['Blend Angus 180g', 'Triple Cheddar', 'Bacon crocante', 'Pão Brioche'],
        filters: ['artesanal', 'premium'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Smash Double Trufado',
        slug: 'smash-double-trufado',
        category_slug: 'burgers-grelhados',
        description: '2 discos de smash 90g com queijo emmental derretido, maionese de trufas brancas e picles da casa.',
        price: 38.00,
        image_url: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&fit=crop',
        ingredients: ['2x Smash 90g', 'Queijo Emmental', 'Maionese trufada', 'Picles artesanal'],
        filters: ['artesanal'],
        is_bestseller: true,
      },
      {
        name: 'Batata Rústica Trufada',
        slug: 'batata-rustica-trufada',
        category_slug: 'porcoes',
        description: 'Batatas com casca fritas na hora, azeite de trufas brancas, parmesão 24 meses e alecrim.',
        price: 28.90,
        image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&fit=crop',
        filters: ['sem_gluten', 'artesanal'],
      },
      {
        name: 'Milkshake Nutella Supremo',
        slug: 'milkshake-nutella-supremo',
        category_slug: 'shakes',
        description: 'Gelato artesanal de baunilha, Nutella pura, Leite Ninho e topo generoso de chantilly.',
        price: 26.00,
        image_url: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&fit=crop',
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'pizzaria',
    name: 'Pizzaria & Forno a Lenha',
    icon: '🍕',
    description: 'Cardápio para pizzarias tradicionais, fornos napolitanos, bordas recheadas e brotos doces.',
    theme: { primary_color: '#E11D48', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&h=500&fit=crop',
    categories: [
      { name: '🔥 Pizzas Tradicionais', slug: 'pizzas-tradicionais', sort_order: 1 },
      { name: '⭐ Especiais Gourmet', slug: 'especiais-gourmet', sort_order: 2 },
      { name: '🍫 Brotos Doces', slug: 'brotos-doces', sort_order: 3 },
      { name: '🍷 Vinhos & Bebidas', slug: 'vinhos-bebidas', sort_order: 4 },
      { name: '🥖 Entradas & Crostinis', slug: 'entradas', sort_order: 5 },
    ],
    products: [
      {
        name: 'Pizza Margherita Di Bufala',
        slug: 'pizza-margherita-di-bufala',
        category_slug: 'pizzas-tradicionais',
        description: 'Molho de tomate pelati italiano, muçarela de búfala fresca, manjericão gigante e azeite extravirgem.',
        price: 69.90,
        image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&fit=crop',
        ingredients: ['Massa Fermentação Natural 48h', 'Muçarela de Búfala', 'Tomate Pelati', 'Manjericão'],
        filters: ['vegetariano', 'artesanal'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Pizza Pepperoni Supreme',
        slug: 'pizza-pepperoni-supreme',
        category_slug: 'pizzas-tradicionais',
        description: 'Molho de tomate artesanal, bastante muçarela especial, fatias de pepperoni crocante e oregano selvagem.',
        price: 74.90,
        promo_price: 64.90,
        image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&fit=crop',
        is_bestseller: true,
      },
      {
        name: 'Pizza Doce Nutella com Morango',
        slug: 'pizza-doce-nutella-morango',
        category_slug: 'brotos-doces',
        description: 'Broto com massa crocante coberta com camada alta de Nutella pura e morangos frescos fatiados.',
        price: 49.90,
        image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&fit=crop',
        is_featured: true,
      },
    ],
  },
  {
    id: 'sushibar',
    name: 'Japonês & Sushi Bar',
    icon: '🍣',
    description: 'Perfeito para restaurantes japoneses, temakerias, sushi bars e combinados omakase.',
    theme: { primary_color: '#06B6D4', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=1200&h=500&fit=crop',
    categories: [
      { name: '🍱 Combinados Omakase', slug: 'combinados', sort_order: 1 },
      { name: '🍣 Sashes & Niguiris', slug: 'sashimis-niguiris', sort_order: 2 },
      { name: '🥢 Temakis Especiais', slug: 'temakis', sort_order: 3 },
      { name: '🔥 Hot Rolls & Uramakis', slug: 'hot-rolls', sort_order: 4 },
      { name: '🍶 Saquês & Drinks', slug: 'saques-drinks', sort_order: 5 },
    ],
    products: [
      {
        name: 'Combinado Omakase (30 Peças)',
        slug: 'combinado-omakase-30',
        category_slug: 'combinados',
        description: '10 Sashimis de Salmão, 6 Niguiris Salmão Trufado, 8 Uramakis Filadélfia e 6 Dyo Trufados com Ovas.',
        price: 119.90,
        promo_price: 99.90,
        image_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&fit=crop',
        ingredients: ['Salmão fresco fresco', 'Azeite trufado', 'Flor de sal', 'Cream Cheese'],
        filters: ['premium', 'sem_gluten'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Temaki Salmão Crispy com Cream Cheese',
        slug: 'temaki-salmao-crispy',
        category_slug: 'temakis',
        description: 'Nori crocante recheado com salmão em cubos, bastante cream cheese e crispy de couve ou alho-poró.',
        price: 36.90,
        image_url: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&fit=crop',
        is_bestseller: true,
      },
      {
        name: 'Hot Roll Ebi Tempura com Tarê',
        slug: 'hot-roll-ebi-tempura',
        category_slug: 'hot-rolls',
        description: '8 peças de sushi empanado e frito na hora, recheado com camarão e cream cheese, finalizado com molho tarê.',
        price: 42.00,
        image_url: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&fit=crop',
      },
    ],
  },
  {
    id: 'cafeteria',
    name: 'Cafeteria & Confeitaria Fine',
    icon: '☕',
    description: 'Para cafeterias de especialidade, boulangeries, docerias finas e casas de chá.',
    theme: { primary_color: '#B8860B', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1200&h=500&fit=crop',
    categories: [
      { name: '☕ Cafés de Especialidade', slug: 'cafes-especiais', sort_order: 1 },
      { name: '🥐 Croissants & Salgados', slug: 'croissants-salgados', sort_order: 2 },
      { name: '🍰 Tortas & Doces Finos', slug: 'tortas-doces', sort_order: 3 },
      { name: '🧋 Bebidas Geladas & Frappés', slug: 'bebidas-geladas', sort_order: 4 },
    ],
    products: [
      {
        name: 'Cappuccino Trufado com Avelã',
        slug: 'cappuccino-trufado-avela',
        category_slug: 'cafes-especiais',
        description: 'Espresso 100% Arábica, leite vaporizado aveludado, borda de Nutella pura e cacau em pó 70%.',
        price: 18.90,
        image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&fit=crop',
        ingredients: ['Espresso Arábica 85+ pts', 'Leite vaporizado', 'Nutella', 'Cacau 70%'],
        filters: ['artesanal', 'premium'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Croissant Francês Brie com Mel',
        slug: 'croissant-brie-mel',
        category_slug: 'croissants-salgados',
        description: 'Croissant folheado com manteiga francesa, recheado com queijo brie derretido e fio de mel de floraranjeira.',
        price: 26.90,
        image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&fit=crop',
        is_bestseller: true,
      },
      {
        name: 'Torta Red Velvet Velvet Cream',
        slug: 'torta-red-velvet',
        category_slug: 'tortas-doces',
        description: 'Fatia de bolo aveludado vermelho com recheio denso de cream cheese e favas de baunilha de Madagascar.',
        price: 24.00,
        image_url: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=800&fit=crop',
        is_featured: true,
      },
    ],
  },
  {
    id: 'acaiteria',
    name: 'Açaíteria & Gelateria',
    icon: '🍧',
    description: 'Desenvolvido para açaíterias, sorveterias, taças recheadas e sucos funcionais.',
    theme: { primary_color: '#8B5CF6', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=1200&h=500&fit=crop',
    categories: [
      { name: '🍧 Copos de Açaí Supremo', slug: 'copos-acai', sort_order: 1 },
      { name: '🍦 Gelatos & Taças', slug: 'gelatos-tacas', sort_order: 2 },
      { name: '🍓 Sucos Naturais & Smoothies', slug: 'sucos-smoothies', sort_order: 3 },
    ],
    products: [
      {
        name: 'Copo Açaí Supremo (500ml)',
        slug: 'copo-acai-supremo-500ml',
        category_slug: 'copos-acai',
        description: 'Açaí puro sem xarope, em camadas com Leite Ninho, morangos frescos, Nutella pura e paçoca crocante.',
        price: 29.90,
        promo_price: 24.90,
        image_url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&fit=crop',
        ingredients: ['Açaí 100% Puro', 'Leite Ninho', 'Nutella', 'Morango fresco'],
        filters: ['sem_gluten', 'fit'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Taça Gelato de Pistache Siciliano',
        slug: 'taca-gelato-pistache',
        category_slug: 'gelatos-tacas',
        description: 'Duas bolas de gelato artesanal de pistache puro, ganache de chocolate branco e pedaços de pistache tostado.',
        price: 34.00,
        image_url: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&fit=crop',
        filters: ['artesanal', 'premium'],
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'bar-boteco',
    name: 'Bar, Boteco & Adega',
    icon: '🍺',
    description: 'Para bares, pubs, adegas, gastrobares e casas noturnas com petiscos e drinks.',
    theme: { primary_color: '#F59E0B', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1200&h=500&fit=crop',
    categories: [
      { name: '🍻 Chopes & Cervejas Trincando', slug: 'chopes-cervejas', sort_order: 1 },
      { name: '🍸 Drinks da Casa', slug: 'drinks', sort_order: 2 },
      { name: '🍗 Porções & Petiscos de Boteco', slug: 'porcoes-petiscos', sort_order: 3 },
      { name: '🍷 Vinhos & Tábua de Frios', slug: 'vinhos-frios', sort_order: 4 },
    ],
    products: [
      {
        name: 'Porção Costelinha BBQ com Fritas',
        slug: 'porcao-costelinha-bbq',
        category_slug: 'porcoes-petiscos',
        description: 'Costela suína assada lentamente por 6 horas, banhada no molho barbecue artesanal e acompanhada de batatas fritas.',
        price: 64.90,
        image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&fit=crop',
        ingredients: ['Costela Suína 700g', 'Molho Barbecue artesanal', 'Batata frita crocante'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Drink Gin Tônica de Frutas Vermelhas',
        slug: 'drink-gin-tonica-frutas-vermelhas',
        category_slug: 'drinks',
        description: 'Gin Tanqueray premium, água tônica artesanal, infusão de frutas vermelhas, zimbo e ramo de alecrim.',
        price: 34.90,
        image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&fit=crop',
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'saudavel-fit',
    name: 'Saudável, Fit & Saladeria',
    icon: '🥗',
    description: 'Focado em restaurantes funcionais, saladerias, marmitas fit e comida saudável.',
    theme: { primary_color: '#10B981', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=1200&h=500&fit=crop',
    categories: [
      { name: '🥗 Bowls & Saladas do Chef', slug: 'bowls-saladas', sort_order: 1 },
      { name: '🌯 Wraps & Sanduíches Leves', slug: 'wraps-sanduiches', sort_order: 2 },
      { name: '🥤 Sucos Detox & Funcionais', slug: 'sucos-detox', sort_order: 3 },
      { name: '🍌 Sobremesas Fit Zero Açúcar', slug: 'sobremesas-fit', sort_order: 4 },
    ],
    products: [
      {
        name: 'Poke Bowl Salmão com Avocado',
        slug: 'poke-bowl-salmao-avocado',
        category_slug: 'bowls-saladas',
        description: 'Cubes de salmão fresco marinado, arroz shari integral, avocado fatiado, edamame, manga e molho ponzu especial.',
        price: 46.90,
        image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&fit=crop',
        ingredients: ['Salmão Marinado', 'Avocado', 'Arroz Integral', 'Edamame', 'Molho Ponzu'],
        filters: ['fit', 'sem_gluten', 'sem_lactose'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Wrap de Frango Grelhado com Homus',
        slug: 'wrap-frango-homus',
        category_slug: 'wraps-sanduiches',
        description: 'Massa folhada integral, peito de frango grelhado desfiado, homus de grão-de-bico, alface, tomate e azeite.',
        price: 29.90,
        image_url: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&fit=crop',
        filters: ['fit', 'sem_lactose'],
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'churrascaria',
    name: 'Churrascaria & Grill',
    icon: '🥩',
    description: 'Para churrascarias, espetinhos, rodízios, steakhouses e restaurantes com fogo de chão.',
    theme: { primary_color: '#DC2626', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=1200&h=500&fit=crop',
    categories: [
      { name: '🥩 Cortes Nobres & Grelhados', slug: 'cortes-grelhados', sort_order: 1 },
      { name: '🍢 Espetinhos da Casa', slug: 'espetinhos', sort_order: 2 },
      { name: '🍟 Acompanhamentos & Saladas', slug: 'acompanhamentos', sort_order: 3 },
      { name: '🥤 Bebidas & Sucos', slug: 'bebidas', sort_order: 4 },
    ],
    products: [
      {
        name: 'Picanha Angus Grelhada (400g)',
        slug: 'picanha-angus-grelhada',
        category_slug: 'cortes-grelhados',
        description: 'Picanha bovina de primeira seleção, grelhada no carvão com sal grosso e manteiga de ervas.',
        price: 98.90,
        promo_price: 84.90,
        image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&fit=crop',
        ingredients: ['Picanha Angus 400g', 'Sal Grosso', 'Manteiga de Ervas', 'Alho assado'],
        filters: ['premium', 'sem_gluten'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Espeto de Coração de Frango (6un)',
        slug: 'espeto-coracao-frango',
        category_slug: 'espetinhos',
        description: 'Corações de frango temperados na vinha d\'alhos, grelhados na brasa com colorau e limão.',
        price: 24.90,
        image_url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&fit=crop',
        is_bestseller: true,
      },
      {
        name: 'Arroz com Farofa & Vinagrete',
        slug: 'arroz-farofa-vinagrete',
        category_slug: 'acompanhamentos',
        description: 'Arroz branco soltinho, farofa de manteiga com bacon tostado e vinagrete fresquinho da casa.',
        price: 18.90,
        image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&fit=crop',
        filters: ['sem_gluten'],
      },
    ],
  },
  {
    id: 'nordestino',
    name: 'Nordestino & Tapiocaria',
    icon: '🫔',
    description: 'Culinária nordestina, tapiocas recheadas, cuscuz, baião de dois e quitutes regionais.',
    theme: { primary_color: '#F97316', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200&h=500&fit=crop',
    categories: [
      { name: '🫔 Tapiocas Artesanais', slug: 'tapiocas', sort_order: 1 },
      { name: '🍛 Pratos Típicos do Nordeste', slug: 'pratos-tipicos', sort_order: 2 },
      { name: '🌽 Cuscuz & Lanches', slug: 'cuscuz-lanches', sort_order: 3 },
      { name: '🍹 Sucos & Vitaminas', slug: 'sucos-vitaminas', sort_order: 4 },
    ],
    products: [
      {
        name: 'Tapioca Carne do Sol com Coalho',
        slug: 'tapioca-carne-sol-coalho',
        category_slug: 'tapiocas',
        description: 'Tapioca artesanal recheada com carne do sol dourada, queijo de coalho grelhado e manteiga de garrafa.',
        price: 24.90,
        promo_price: 19.90,
        image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&fit=crop',
        ingredients: ['Goma de Tapioca', 'Carne do Sol', 'Queijo Coalho', 'Manteiga de Garrafa'],
        filters: ['sem_gluten', 'artesanal'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Baião de Dois Completo',
        slug: 'baiao-de-dois-completo',
        category_slug: 'pratos-tipicos',
        description: 'Arroz com feijão verde, queijo de coalho derretido, carne de charque e linguiça calabresa.',
        price: 36.90,
        image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&fit=crop',
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'padaria',
    name: 'Padaria & Hortifrúti',
    icon: '🥖',
    description: 'Para padarias, feiras, mercadinhos, casa de pão de queijo e hortifrútis com café da manhã.',
    theme: { primary_color: '#D97706', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=1200&h=500&fit=crop',
    categories: [
      { name: '🥖 Pães Fresquinhos do Dia', slug: 'paes', sort_order: 1 },
      { name: '☕ Café da Manhã & Combos', slug: 'cafe-manha', sort_order: 2 },
      { name: '🧀 Salgados & Folhados', slug: 'salgados', sort_order: 3 },
      { name: '🍰 Bolos & Doces Caseiros', slug: 'bolos-doces', sort_order: 4 },
      { name: '🥛 Bebidas & Vitaminas', slug: 'bebidas', sort_order: 5 },
    ],
    products: [
      {
        name: 'Pão Francês Quentinho (6 unidades)',
        slug: 'pao-frances-quentinho',
        category_slug: 'paes',
        description: 'Pão francês tradicional assado na hora, crocante por fora e macio por dentro. Sai da fornada a cada 30 min.',
        price: 8.90,
        image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&fit=crop',
        filters: ['artesanal'],
        is_bestseller: true,
      },
      {
        name: 'Combo Café da Manhã Completo',
        slug: 'combo-cafe-manha',
        category_slug: 'cafe-manha',
        description: 'Café com leite, 2 pães com manteiga, 1 salgado da vitrine e suco natural de laranja.',
        price: 24.90,
        promo_price: 19.90,
        image_url: 'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=800&fit=crop',
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Coxinha de Frango com Catupiry',
        slug: 'coxinha-frango-catupiry',
        category_slug: 'salgados',
        description: 'Massa macia recheada com frango desfiado temperado e catupiry cremoso, frita na hora.',
        price: 6.90,
        image_url: 'https://images.unsplash.com/photo-1583599766232-1e2e3b73d082?w=800&fit=crop',
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'frango-fastfood',
    name: 'Frango Frito & Fast Food',
    icon: '🍗',
    description: 'Para franguerias, chicken shops, fast food de frango, asas empanadas e combos família.',
    theme: { primary_color: '#EAB308', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1626082927389-6cd097cee6a0?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=1200&h=500&fit=crop',
    categories: [
      { name: '🍗 Frango Frito & Empanado', slug: 'frango-frito', sort_order: 1 },
      { name: '🍔 Sanduíches & Wraps', slug: 'sanduiches', sort_order: 2 },
      { name: '🍟 Combos & Promoções', slug: 'combos', sort_order: 3 },
      { name: '🌶️ Asinhas & Drumettes', slug: 'asinhas', sort_order: 4 },
      { name: '🥤 Bebidas & Milkshakes', slug: 'bebidas-shakes', sort_order: 5 },
    ],
    products: [
      {
        name: 'Balde Frango Crocante (8 peças)',
        slug: 'balde-frango-crocante-8',
        category_slug: 'frango-frito',
        description: 'Frango empanado no tempero especial da casa, fresco e crocante. Acompanha molho da casa.',
        price: 64.90,
        promo_price: 54.90,
        image_url: 'https://images.unsplash.com/photo-1626082927389-6cd097cee6a0?w=800&fit=crop',
        ingredients: ['Frango Empanado Especial', 'Tempero Secreto', 'Molho da Casa'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Combo 1 — Sanduíche + Fritas + Bebida',
        slug: 'combo-1-sanduiche-fritas-bebida',
        category_slug: 'combos',
        description: 'Sanduíche de frango crocante com salada + batata frita crocante + refrigerante 500ml.',
        price: 38.90,
        promo_price: 32.90,
        image_url: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&fit=crop',
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'marmitaria',
    name: 'Marmitaria & Prato Feito',
    icon: '🍱',
    description: 'Para marmitarias, quentinhas, restaurantes por quilo, PF comercial e delivery de refeições.',
    theme: { primary_color: '#16A34A', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&h=500&fit=crop',
    categories: [
      { name: '🍽️ Pratos Feitos do Dia', slug: 'pratos-feitos', sort_order: 1 },
      { name: '🥩 Marmitas Especiais', slug: 'marmitas-especiais', sort_order: 2 },
      { name: '🥗 Saladas & Petiscos', slug: 'saladas', sort_order: 3 },
      { name: '🍮 Sobremesas Caseiras', slug: 'sobremesas', sort_order: 4 },
    ],
    products: [
      {
        name: 'PF Completo — Frango, Arroz, Feijão e Salada',
        slug: 'pf-frango-arroz-feijao-salada',
        category_slug: 'pratos-feitos',
        description: 'Peito de frango grelhado temperado, arroz branco, feijão carioca e saladinha temperada da casa.',
        price: 22.90,
        promo_price: 18.90,
        image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&fit=crop',
        filters: ['sem_gluten'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Marmita Fitness — Proteico Sem Carboidrato',
        slug: 'marmita-fitness-proteico',
        category_slug: 'marmitas-especiais',
        description: 'Peito de frango, ovo estrelado, batata doce, brócolis no vapor e mix de folhas.',
        price: 28.90,
        image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&fit=crop',
        filters: ['fit', 'sem_gluten', 'sem_lactose'],
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'italiana',
    name: 'Italiana & Massas Artesanais',
    icon: '🍝',
    description: 'Restaurantes italianos, cantinas, trattorie, massas frescas, risotos e tiramisu.',
    theme: { primary_color: '#059669', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=1200&h=500&fit=crop',
    categories: [
      { name: '🍝 Massas Frescas Artesanais', slug: 'massas', sort_order: 1 },
      { name: '🍕 Pizzas & Calzones', slug: 'pizzas', sort_order: 2 },
      { name: '🫕 Risotos', slug: 'risotos', sort_order: 3 },
      { name: '🥗 Antepastos & Bruschetas', slug: 'antepastos', sort_order: 4 },
      { name: '🍷 Vinhos & Digestivos', slug: 'vinhos', sort_order: 5 },
    ],
    products: [
      {
        name: 'Tagliatelle ao Funghi Porcini',
        slug: 'tagliatelle-funghi-porcini',
        category_slug: 'massas',
        description: 'Massa fresca artesanal com ragu de funghi porcini reidratado, creme de leite fresco e parmesão 24 meses.',
        price: 62.90,
        image_url: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&fit=crop',
        ingredients: ['Tagliatelle fresco', 'Funghi Porcini', 'Creme Fresco', 'Parmesão 24m'],
        filters: ['artesanal', 'vegetariano'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Risoto de Camarão com Açafrão',
        slug: 'risoto-camarao-acafrao',
        category_slug: 'risotos',
        description: 'Arroz arbóreo cremoso, camarões grelhados na manteiga, açafrão importado e toque de limão siciliano.',
        price: 78.90,
        promo_price: 68.90,
        image_url: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&fit=crop',
        filters: ['premium', 'sem_gluten'],
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'mexicana',
    name: 'Mexicana & Tex-Mex',
    icon: '🌮',
    description: 'Para restaurantes mexicanos, burritos, tacos, nachos, margaritas e comida Tex-Mex.',
    theme: { primary_color: '#7C3AED', mode: 'dark', style: 'vibrant' },
    defaultLogo: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=1200&h=500&fit=crop',
    categories: [
      { name: '🌮 Tacos & Burritos', slug: 'tacos-burritos', sort_order: 1 },
      { name: '🧀 Nachos & Quesadillas', slug: 'nachos-quesadillas', sort_order: 2 },
      { name: '🥑 Guacamoles & Entradas', slug: 'entradas', sort_order: 3 },
      { name: '🍹 Margaritas & Drinks', slug: 'drinks', sort_order: 4 },
    ],
    products: [
      {
        name: 'Burrito Carnitas de Porco (Grande)',
        slug: 'burrito-carnitas-grande',
        category_slug: 'tacos-burritos',
        description: 'Tortilha extra grande, porco desfiado marinado em chipotle, arroz mexicano, feijão preto, queijo cheddar e sour cream.',
        price: 44.90,
        promo_price: 38.90,
        image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&fit=crop',
        ingredients: ['Tortilha XL', 'Carnitas de Porco', 'Arroz Mexicano', 'Feijão Preto', 'Sour Cream'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Nachos Supremos com Guacamole',
        slug: 'nachos-supremos-guacamole',
        category_slug: 'nachos-quesadillas',
        description: 'Tortilha chips crocante, guacamole fresco, queijo cheddar derretido, jalapeños, sour cream e pico de gallo.',
        price: 38.90,
        image_url: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&fit=crop',
        filters: ['vegetariano'],
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'doceria',
    name: 'Doceria & Chocolateria',
    icon: '🍫',
    description: 'Para docerias finas, chocolaterias, brigadeiros gourmet, bolos decorados e candy shops.',
    theme: { primary_color: '#92400E', mode: 'dark', style: 'luxury' },
    defaultLogo: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=1200&h=500&fit=crop',
    categories: [
      { name: '🍫 Chocolates & Trufas Finas', slug: 'chocolates-trufas', sort_order: 1 },
      { name: '🎂 Bolos Decorados & Tortas', slug: 'bolos-tortas', sort_order: 2 },
      { name: '🍬 Brigadeiros Gourmet', slug: 'brigadeiros', sort_order: 3 },
      { name: '🧁 Cupcakes & Mini Doces', slug: 'cupcakes', sort_order: 4 },
    ],
    products: [
      {
        name: 'Caixa Trufas Belga Sortidas (12un)',
        slug: 'caixa-trufas-belga-sortidas',
        category_slug: 'chocolates-trufas',
        description: 'Trufas artesanais de chocolate belga 70%, recheios sortidos: caramelo salgado, maracujá, avelã e framboesa.',
        price: 68.00,
        promo_price: 58.00,
        image_url: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&fit=crop',
        ingredients: ['Chocolate Belga 70%', 'Caramelo Salgado', 'Framboesa', 'Avelã'],
        filters: ['artesanal', 'premium'],
        is_bestseller: true,
        is_featured: true,
      },
      {
        name: 'Brigadeiro Gourmet de Pistache (6un)',
        slug: 'brigadeiro-gourmet-pistache',
        category_slug: 'brigadeiros',
        description: 'Brigadeiro cremoso de leite condensado com pasta de pistache puro, finalizado em granulado de pistache tostado.',
        price: 34.90,
        image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&fit=crop',
        filters: ['artesanal'],
        is_bestseller: true,
      },
    ],
  },
  {
    id: 'frutos-do-mar',
    name: 'Frutos do Mar & Peixaria',
    icon: '🦞',
    description: 'Para peixarias, restaurantes de frutos do mar, moquecas, camarões e mariscos.',
    theme: { primary_color: '#0891B2', mode: 'dark', style: 'glass' },
    defaultLogo: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=300&h=300&fit=crop',
    defaultBanner: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=1200&h=500&fit=crop',
    categories: [
      { name: '🦞 Frutos do Mar Premium', slug: 'frutos-do-mar', sort_order: 1 },
      { name: '🐟 Peixes & Filés Grelhados', slug: 'peixes', sort_order: 2 },
      { name: '🫕 Caldeiradas & Moquecas', slug: 'caldeiradas', sort_order: 3 },
      { name: '🍻 Bebidas & Caipirinhas', slug: 'bebidas', sort_order: 4 },
    ],
    products: [
      {
        name: 'Meia Lagosta Grelhada com Manteiga',
        slug: 'meia-lagosta-grelhada',
        category_slug: 'frutos-do-mar',
        description: 'Meia lagosta fresca grelhada na chapa, manteiga de ervas finas, alho dourado e limão siciliano.',
        price: 149.90,
        image_url: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&fit=crop',
        ingredients: ['Lagosta Fresca 500g', 'Manteiga de Ervas', 'Alho Dourado', 'Limão Siciliano'],
        filters: ['premium', 'sem_gluten'],
        is_featured: true,
        is_bestseller: true,
      },
      {
        name: 'Moqueca de Camarão Baiana (para 2)',
        slug: 'moqueca-camarao-baiana',
        category_slug: 'caldeiradas',
        description: 'Camarões graúdos, leite de coco, azeite de dendê, pimenta dedo de moça e coentro. Acompanha pirão e arroz.',
        price: 119.90,
        promo_price: 99.90,
        image_url: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&fit=crop',
        filters: ['sem_gluten'],
        is_bestseller: true,
      },
    ],
  },
];

